language: node_js
deploy:
  provider: heroku
  strategy: git
  app: immense-badlands-52446
  api_key:
    secure: Ni9mkcZsO1sBx7NethUoGSZeM6r75uXYyvAQbCtfC1HHBPhNIForv0PTLojMXfUR6YTJyMyL3uoddGGauFlfQhMjIRrSo9B+Bp6HXdVOboa3P7Jy1+X8z0tzvv4o3cwoCjDtDkA5FktYBGoFg0RVJmvNmmvqkMy+SLOM2Qxp4xFc6pLjtd2bTS4w+8PDkrJwuxpiaMg5mpBYxvG0JRfmh/ZphcFyBKpTO9FSswI7EX4auXZUDJkkFHwk5b2cI1sfzduLbzCMc+6Vizhvsq0mrS3MR9AYvBUoYKDrfiTX1iidyBZa2WRTIFK3/TfXyioZ4CNYq8RzhZeKLYqzrenzSmljzWtvCFaGYrHJtuVijlMivk5gP+wDpOoVXR9tyFXgIaghT9bgMjacEePVOvqeldzjXyvdiZC39Tn4XIbmNvw54/eGI2L9jKGU5gIkTjSDE3sH+/w4GJQ9dv/4jUFJ8t2MdwSN4FH27kq657XPEcbFR8dQlmhfe5/OqIxChVPZDfHVep/2eUiBoQ0PvPNNbKoeSK2TmPlQvhLAGFzpcv+DuvdfvOZ/tCT6mIa8vVCGbLM3jp6p3xMoLpJcFoQReKnHvH9ogVnTiFkyKK+CDwVRssI67BboiomS0bC/T/m1voh29lDdCpgJxOpkOo0sNeEPzAyNT9YN9r+SxK747ig=
